/*import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/
//import './styles/globals.css';  // Global styles
//import 'bootstrap/dist/css/bootstrap.min.css';  // Bootstrap
//import 'owl.carousel/dist/assets/owl.carousel.min.css';  // Owl Carousel
//import 'owl.carousel/dist/assets/owl.theme.default.min.css';  // Owl Carousel Theme
import Footer from './Components/Footer/Footer'
import Navbar from './Components/Navbar/Navbar'
export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>MBS Pharmas</title>
        <link rel="icon" href="/assets/img/favicon.ico" />
      </head>
      <body>
        <Navbar/>

        {children}

        <Footer/>
      </body>
    </html>
  );
}
